steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=my-keyring
  - --key=npm-key
  volumes:
  - name: 'home'
    path: /root/

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['build']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['publish']
#   env:
#   - HOME=/root/
#   volumes:
#   - name: 'home'
#     path: /root/

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo $(cat sdk/package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]') > /workspace/Latest_Version.txt
    npm version echo $(cat /workspace/Latest_Version.txt)-alpha
    npm install
    npm build
    npm publish --tag beta
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/


