steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/git'
  args: ['config', '--global', 'user.email', 'sumits@incubxperts.com']

- name: 'gcr.io/cloud-builders/git'
  args: ['config', '--global', 'user.name', 'sumits096']

- name: 'gcr.io/cloud-builders/npm'
  args: ['version','prepatch']

# - name: 'gcr.io/cloud-builders/git'
#   args: ['version','prepatch']

- name: 'gcr.io/cloud-builders/git'
  id: Copy to production branch
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x && \
    # git log --format=%B -n 1 $COMMIT_SHA
    # git merge FETCH_HEAD
    # git tag v1.2.4
    # git push --tags -f
    npm version patch
    git push origin version changes
