steps:
- name: 'gcr.io/cloud-builders/git'
  id: Copy to production branch
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    git config --global --add user.name 'sumits096'
    git config --global --add user.email 'sumits@incubxperts.com'
    npm version patch -m "[RELEASE] %s"
    git merge FETCH_HEAD
    git push
