steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=my-keyring
  - --key=npm-key
  volumes:
  - name: 'home'
    path: /root/

- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Pushing changes to git config repo ..."
    git show-ref
    git config --global user.name sumit096
    git config --global user.email sumits@incubxperts.com
    
    echo $(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]') > /workspace/Latest_Version.txt
    echo $(cat /workspace/Latest_Version.txt)

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm build
    npm publish --tag beta
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/


