# steps:

# # Edit Kustomize layer in config repo and push changes
# - name: gcr.io/cloud-builders/git
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     # echo "Cloning repo ..."
#     # eval `ssh-agent -s`
#     # # ssh-add
#     # ssh-add ~/.ssh/9.pub
#     # ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
#     # git clone --depth 1 https://github.com/sumits096/ix-npm-versioning.git
#     # echo ${BRANCH_NAME}
#     # cd ix-pm-versioning
#     # ls
#     # sed -i "s|newTag: .*|newTag: $SHORT_SHA"
#     echo "Pushing changes to git config repo ..."
#     # git show-ref
#     git config --global user.name sumits096
#     git config --global user.email sumits@incubxperts.com
#     echo $(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
#     touch README
#     git add .
#     git commit -m 'reinitialized files'
#     # git tag v1.2.4
#     # git push origin version-changes --force
#     git push origin --force
#     # git push origin https://github.com/sumits096/ix-npm-versioning.git version-changes --tags -f
#     # git add -A
#     # git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
#     # git push origin https://github.com/sumits096/ix-npm-versioning.git HEAD:${BRANCH_NAME}


# name: Version Increment

steps:
  - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
    run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

  - name: Get Current version
    run: |
          echo "::set-env name=Latest_Version::$(echo $(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]'))"

  - name: Get main branch version
    run: |
          git checkout main
          git pull origin ${{ github.base_ref }}
          echo "::set-env name=Previous_Version::$(echo $(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]'))"

  - name: Verify and Patch version
    if: env.Latest_Version == env.Previous_Version
    run: |
          git config --global --add user.name 'sumits096'
          git config --global --add user.email 'sumits@incubxperts.com'
          npm version patch -m "[RELEASE] %s"
          git merge FETCH_HEAD
          git push

  - name: Add tags to github
    run: |
          git config --global --add user.name 'sumits096'
          git config --global --add user.email 'sumits@incubxperts.com'
          git tag v$Latest_Version
          git push --tags -f
