# steps:
# - name: gcr.io/cloud-builders/git
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     git config --global user.name sumits096
#     git config --global user.email sumits@incubxperts.com

#     git tag v1.2.10 
#     touch README
#     git add .
#     git commit -m 'message'

#     git branch -M main
#     git remote set-url origin https://sumits096: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@github.com/sumits096/ix-npm-versioning.git
#     echo "Pushing changes to git repo ..."
#     # npm version patch 
#     git push -u origin main

steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Pushing changes to git config repo ..."
    git show-ref
    git config --global user.name ix-pankajk
    git config --global user.email prkhajone95@gmail.com
    git tag v1.2.10
    touch README
    git diff
    git add .
    git commit -m 'message'
    git branch -M dev-docker-cicd
    git remote set-url origin https://ix-pankajk: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@github.com/ix-pankajk/ix-terraform-cicd.git
    git push -u origin dev-docker-cicd
