steps:
# - name: gcr.io/cloud-builders/git
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     git config --global user.name sumits096
#     git config --global user.email sumits@incubxperts.com

#     git tag v1.2.10 
#     touch README
#     git add .
#     git commit -m 'message'

#     git branch -M main
#     git remote set-url origin https://sumits096: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@github.com/sumits096/ix-npm-versioning.git
#     echo "Pushing changes to git config repo ..."
#     # npm version patch 
#     git push -u origin main

- name: 'gcr.io/cloud-builders/git'
  args: ['branch','-M', 'dev-docker-cicd']

- name: 'gcr.io/cloud-builders/git'
  args: ['remote','set-url','origin','https://ix-pankajk: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@github.com/ix-pankajk/ix-terraform-cicd.git']

- name: 'gcr.io/cloud-builders/git'
  args: ['push','-u','origin','dev-docker-cicd']
