steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=my-keyring
  - --key=npm-key
  volumes:
  - name: 'home'
    path: /root/

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

-  name: 'gcr.io/cloud-builders/git'
  args: ['config', '--global', 'user.email', 'prkhajone95@gmail.com']

- name: 'gcr.io/cloud-builders/git'
  args: ['config', '--global', 'user.name', 'ix-pankajk']

- name: 'gcr.io/cloud-builders/npm'
  args: ['version','prepatch']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']

- name: 'gcr.io/cloud-builders/npm'
  args: ['publish']
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/
