steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/git'
#   args: ['config', '--global', 'user.email', 'sumits@incubxperts.com']

# - name: 'gcr.io/cloud-builders/git'
#   args: ['config', '--global', 'user.name', 'sumits096']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['version','prepatch']

# - name: 'gcr.io/cloud-builders/git'
#   args: ['version','prepatch']

# - name: 'gcr.io/cloud-builders/git'
#   id: Patch version to feature branch
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     set -x && \
#     # git log --format=%B -n 1 $COMMIT_SHA
#     # git merge FETCH_HEAD
#     # npm version patch
#     # git push origin HEAD:refs/heads/version-changes --force
#     # git remote rm origin
#     # git remote add origin 'git@github.com:sumits096/ix-npm-versioning.git'
#     git tag v1.2.4
#     git push origin --tags -f

# Edit Kustomize layer in config repo and push changes
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # echo "Cloning repo ..."
    git clone --depth 1 git@github.com:sumits096/ix-npm-versioning
    # echo ${BRANCH_NAME}
    cd ix-pm-versioning
    # ls
    # sed -i "s|newTag: .*|newTag: $SHORT_SHA"
    echo "Pushing changes to git config repo ..."
    git config --global user.name sumits096
    git config --global user.email sumits@incubxperts.com
    git tag v1.2.4
    git push origin HEAD
    # git add -A
    # git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
    # git push origin git@github.com:sumits096/ix-npm-versioning.git HEAD:${BRANCH_NAME}

# - name: 'gcr.io/cloud-builders/git'
#   args: ['push','origin','https://sumits096:Sumit@Incub123@github.com:sumits096/ix-npm-versioning.git','--tags', '-f']
