steps:

# Edit Kustomize layer in config repo and push changes
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # echo "Cloning repo ..."
    # eval `ssh-agent -s`
    # # ssh-add
    # ssh-add ~/.ssh/9.pub
    # ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    # git clone --depth 1 https://github.com/sumits096/ix-npm-versioning.git
    # echo ${BRANCH_NAME}
    # cd ix-pm-versioning
    # ls
    # sed -i "s|newTag: .*|newTag: $SHORT_SHA"
    echo "Pushing changes to git config repo ..."
    # git show-ref
    git config --global user.name sumits096
    git config --global user.email sumits@incubxperts.com
    # git checkout main
    echo $(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
    # touch README
    # git add .
    # git commit -m 'reinitialized files'
    # git push -u origin master
    git tag v1.2.411
    # git push origin version-changes --force

    # git branch -M dev-docker-cicd
    git remote set-url origin https://sumits096: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@sumits096/ix-npm-versioning.git
    git push -u origin version-changes --tags

    # git push origin https://github.com/sumits096/ix-npm-versioning.git version-changes --tags -f
    # git add -A
    # git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
    # git push origin https://github.com/sumits096/ix-npm-versioning.git HEAD:${BRANCH_NAME}
