import { CaseLogResponseModel } from '../../src/core/models';

export const caseLogList = [    
    {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-N7G',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'test',
        interaction_event: '{"body": {"data": "test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'test',
        created: '2022-02-14 03:35:16',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-7PT',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'test',
        interaction_event: '{"body": {"data": "test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'test',
        created: '2022-02-14 03:19:57',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-4BN',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hello there Boomtown-IX test',
        interaction_event: '{"body": {"data": "Hello there Boomtown-IX test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hello there Boomtown-IX test',
        created: '2022-02-11 04:46:14',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-AH6',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hello IX test',
        interaction_event: '{"body": {"data": "Hello IX test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hello IX test',
        created: '2022-02-10 02:20:53',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-Y9N',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hello IX test',
        interaction_event: '{"body": {"data": "Hello IX test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hello IX test',
        created: '2022-02-10 02:09:20',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-AHP',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hello IX test',
        interaction_event: '{"body": {"data": "Hello IX test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hello IX test',
        created: '2022-02-10 02:07:49',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-CSP',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hello IX test',
        interaction_event: '{"body": {"data": "Hello IX test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hello IX test',
        created: '2022-02-09 03:59:03',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-A6X',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hi test-ix',
        interaction_event: '{"body": {"data": "Hi test-ix", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hi test-ix',
        created: '2022-02-09 03:54:35',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-MDJ',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'test-ix',
        interaction_event: '{"body": {"data": "test-ix", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'test-ix',
        created: '2022-02-08 22:08:02',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-DMZ',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Hi, test',
        interaction_event: '{"body": {"data": "Hi, test", "type": "text"}, "refs": {"objects": [], "sources": []}, "type": {"id": "note-added", "label": "Note Added"}, "log_id": null, "created": null, "category": {"id": "case-action", "label": "Case Action"}}',
        notes: 'Hi, test',
        created: '2022-02-08 03:40:50',
        event_category: 'case-action',
        event_category_label: 'Case Action',
        event_type: 'note-added',
        event_type_label: 'Note Added',
        fromIssueSave: false,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-AT4',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Set unclaimed_sent to 1',
        interaction_event: null,
        notes: '',
        created: '2021-10-12 20:23:05',
        event_category: null,
        event_category_label: 'Case Update',
        event_type: null,
        event_type_label: 'Case Update',
        fromIssueSave: false,
        c__interaction_event: null,
        _highlighted: false,
        _highlightmap: {}
      },
      {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-LXP',
        issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        users_full_name: '',
        users_nickname: '',
        users_certifications: [],
        diff_log: 'Assigned to Team AutomationOrg',
        interaction_event: null,
        notes: 'Assigned to Team AutomationOrg',
        created: '2021-10-12 20:13:35',
        event_category: null,
        event_category_label: 'Case Update',
        event_type: null,
        event_type_label: 'Case Update',
        fromIssueSave: false,
        c__interaction_event: null,
        _highlighted: false,
        _highlightmap: {}
      }
];

export const caseLogResponse = {
    success: true,
    totalCount: 12,
    returned: caseLogList.length,
    pages: 0,
    results: JSON.parse(JSON.stringify(caseLogList)),
    current_server_time: Date.now().toString(),
};

export const createCaseLogResponse = {
  success: true,
  totalCount: 1,
  returned: 1,
  pages: 0,
  results: [
    {
      id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-Z4M',
      issues_id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
      users_full_name: '',
      users_nickname: '',
      users_certifications: [],
      diff_log: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-N7G',
      interaction_event: '{\"body\": {\"data\": \"0059b314-44e7-4f1f-a3dc-8046ac5388d4-N7G\", \"type\": \"text\"}, \"refs\": {\"objects\": [], \"sources\": []}, \"type\": {\"id\": \"note-added\", \"label\": \"Note Added\"}, \"log_id\": null, \"created\": null, \"category\": {\"id\": \"case-action\", \"label\": \"Case Action\"}}',
      notes: '0059b314-44e7-4f1f-a3dc-8046ac5388d4-N7G',
      created: '2022-02-14 21:11:05',
      event_category: 'case-action',
      event_category_label: 'Case Action',
      event_type: 'note-added',
      event_type_label: 'Note Added',
      fromIssueSave: false
    }
  ],
  'current_server_time': '2022-02-15T05:11:05+0000'
};

export const caseLogDeleteResponse: CaseLogResponseModel = {
  success: true,
  current_server_time: '2022-02-15T04:46:03.421Z',
  totalCount: 11,
  returned: 11,
  pages: 0,
  message: 'string',
  results: JSON.parse(JSON.stringify(caseLogList)),
};

export const caseLogErrorResponse = {
    success: false,
    errorType: 'FileNotFoundException',
    message: 'Object Not Found for members 0059b314-44e7-4f1f-a3dc-8046ac5388d4',
    current_server_time: '2022-02-10T05:03:27+0000',
};
