import {
    CaseDeEscalateOptions,
    CaseEscalateOptions,
    CasesCreateRequest,
    CasesInline,
    CasesInline0,
    CasesMetadata,
} from '../../src/core/entity';
import {
    CaseChatHistoryModel,
    CaseChatHistoryResponseModel,
    CaseChatHistoryTranscriptModel,
    CasesModel,
    CaseStatusHistoryModel,
    CaseStatusHistoryResponseModel,
} from '../../src/core/models';

export const casesList = [
    {
        id: '0059b314-44e7-4f1f-a3dc-8046ac5388d4',
        comm_id: 'NJ2YLQ',
        remote_id: '',
        display_name: '',
        reference_num: '5388D4',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:12:39',
        updated: '2021-10-12 20:23:05',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '007027ee-b382-4f55-b13e-e4424e11d855',
        comm_id: 'QK3QEL',
        remote_id: '',
        display_name: '',
        reference_num: '11D855',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 19:58:51',
        updated: '2022-02-07 00:11:53',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '01153e5d-0248-4275-b7c5-78a33dd7cff2',
        comm_id: 'CLXPAJ',
        remote_id: '',
        display_name: '',
        reference_num: 'D7CFF2',
        type: 'Support',
        resolution: 'Completed',
        job: 'Not Started',
        details: '',
        status: 'Resolved',
        created: '2021-10-12 19:58:56',
        updated: '2022-02-07 00:23:26',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '016c1f5d-0553-4a7d-9b93-0f6d768419a3',
        comm_id: '2FZ8S6',
        remote_id: '',
        display_name: '',
        reference_num: '8419A3',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:02:53',
        updated: '2021-10-12 20:33:02',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '01eb822d-3587-45ab-9e35-0a39525164ff',
        comm_id: null,
        remote_id: '',
        display_name: '',
        reference_num: '5164FF',
        type: 'Support',
        resolution: 'Canceled',
        job: 'Not Started',
        details: '',
        status: 'Canceled',
        created: '2021-10-12 20:01:08',
        updated: '2022-02-07 00:15:25',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '023febe9-893f-4e0b-9827-fe5ee04a5abc',
        comm_id: '86E3BP',
        remote_id: '',
        display_name: '',
        reference_num: '4A5ABC',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:13:32',
        updated: '2021-10-12 20:24:06',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '024f72b1-50b6-498f-9924-6b2d4ab2ac60',
        comm_id: 'W7HL6Z',
        remote_id: '',
        display_name: '',
        reference_num: 'B2AC60',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:02:05',
        updated: '2021-10-12 20:43:02',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '02615d9c-debd-4c33-852e-bfaaa64df537',
        comm_id: '7N8FWZ',
        remote_id: '',
        display_name: '',
        reference_num: '4DF537',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:00:05',
        updated: '2021-10-12 20:11:01',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '02c4ddc5-edc6-4d73-af50-e3245ebadd16',
        comm_id: '68EW8L',
        remote_id: '',
        display_name: '',
        reference_num: 'BADD16',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:04:56',
        updated: '2021-10-12 20:25:06',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
    {
        id: '02fcb243-166b-476b-a10c-44733013fa4a',
        comm_id: 'QWUTM2',
        remote_id: '',
        display_name: '',
        reference_num: '13FA4A',
        type: 'Support',
        resolution: 'Not Set',
        job: 'Not Started',
        details: '',
        status: 'New',
        created: '2021-10-12 20:00:06',
        updated: '2021-10-12 20:11:02',
        scheduled_time: null,
        enroute_time: null,
        arrival_time: null,
        departure_time: null,
        user_agent: 'Web Connect (UZT-LWW)',
        idr_isq: '',
        tech_support_minutes: 0,
        unmanaged: false,
        automationorg_case_custom_field_1: null,
        automationorg_case_custom_field_3: null,
        automationorg_case_custom_field_4: null,
        automationorg_case_custom_field_5: null,
        automationorg_case_custom_field_6: null,
        automationorg_case_custom_field_7: null,
        automationorg_case_custom_field_8: null,
        automationorg_case_custom_field_9: null,
        automationorg_case_custom_field_10: null,
        automationorg_case_custom_field_11: null,
        automationorg_case_custom_field_12: null,
        automationorg_case_custom_field_13: null,
        automationorg_case_custom_field_14: null,
        automationorg_case_custom_field_15: null,
        automationorg_case_custom_field_16: null,
        automationorg_case_custom_field_17: null,
        automationorg_case_private_custom_field_1: null,
        automationorg_case_custom_field_2_ecosystem: null,
        special_notes: '',
        journey_id: null,
        journey_data: [],
        journey_stage: null,
        category: '',
        tags: [],
        category_new: null,
        users_id: '',
        owner_org_team_id: 'UZT-LWW',
        sponsor_org_team_id: null,
        idr_process: '',
        idr_resolution: '',
        metadata_values: {
            preferred_install_date: '',
            preferred_time_frame: 'AM',
            alternate_install_date: '',
            alternate_time_frame: '',
            number_of_pos_devices: 0,
        },
        members_devices: [],
        kb_articles: [],
        external_id: '',
        customer_id: 'C8J8AE',
        members_id: 'C8J8AE',
        customer_name: null,
        members_name: null,
        customer_email: '123abc@boop.com',
        members_email: '123abc@boop.com',
        customer_user_id: 'C8J8AE-UEU',
        members_users_id: 'C8J8AE-UEU',
        customer_user_name: 'test',
        members_users_name: 'test',
        customer_user_email: '123abc@boop.com',
        members_users_email: '123abc@boop.com',
        customer_location_id: 'C8J8AE-T2Q',
        members_locations_id: 'C8J8AE-T2Q',
        customer_location_name: '',
        members_locations_name: '',
        customer_location_merchant_ids: [],
        members_locations_merchant_ids: [],
        isRated: false,
    },
];

export const casesResponse = {
    success: true,
    totalCount: 108,
    returned: casesList.length,
    pages: 3,
    results: JSON.parse(JSON.stringify(casesList)),
    current_server_time: Date.now().toString(),
};

export const casesInline = {
    id: '',
    productId: '',
    make: '',
    model: '',
    nickname: '',
} as CasesInline;

export const casesInline0 = {
    id: '',
    title: '',
    url: '',
} as CasesInline0;

export const casesMetadata = {
    preferredInstallDate: '2021-10-12',
    preferredTimeFrame: '',
    alternateInstallDate: 'AM',
    alternateTimeFrame: '',
    numberOfPosDevices: 0,
} as CasesMetadata;

export const createPayload = {
    id: '',
    referenceNum: '13FA4A',
    remoteId: '',
    displayName: '',
    customerId: '46YSFE',
    customerName: 'Automation-3sbu266',
    customerEmail: 'bminchinton13@list-manage.com',
    customerLocationId: '46YSFE-7ME',
    customerLocationName: 'Automation-Szum269',
    customerContactId: '46YSFE-4FZ',
    customerContactName: 'Giuseppe',
    customerContactEmail: 'gkefford1k@stanford.edu',
    userId: '46YSFE-4FZ',
    externalId: '',
    type: 'Support',
    category: '',
    details: '',
    status: 'New',
    job: '',
    resolution: 'Not Set',
    created: Date.now().toString(),
    updated: Date.now().toString(),
    scheduledTime: '',
    enrouteTime: '',
    arrivalTime: '',
    departureTime: '',
    idrIsq: '',
    idrProcess: '',
    idrResolution: '',
    techSupportMinutes: 0,
    specialNotes: '',
    unmanaged: false,
    ownerOrgTeamId: '',
    sponsorOrgTeamId: '',
    tags: ['Documentation'],
    categoryNew: '',
    membersDevices: [casesInline],
    kbArticles: [casesInline0],
    metadataValues: casesMetadata,
};

export const updatePayload = {
    id: '02fcb243-166b-476b-a10c-44733013fa4a',
    referenceNum: '13FA4A',
    remoteId: '',
    displayName: '',
    customerId: '46YSFE',
    customerName: 'Automation-3sbu266',
    customerEmail: 'bminchinton13@list-manage.com',
    customerLocationId: '46YSFE-7ME',
    customerLocationName: 'Automation-Szum269',
    customerContactId: '46YSFE-4FZ',
    customerContactName: 'Giuseppe',
    customerContactEmail: 'gkefford1k@stanford.edu',
    userId: '46YSFE-4FZ',
    externalId: '',
    type: 'Support',
    category: '',
    details: '',
    status: 'New',
    job: '',
    resolution: 'Not Set',
    created: Date.now().toString(),
    updated: Date.now().toString(),
    scheduledTime: '',
    enrouteTime: '',
    arrivalTime: '',
    departureTime: '',
    idrIsq: '',
    idrProcess: '',
    idrResolution: '',
    techSupportMinutes: 0,
    specialNotes: '',
    unmanaged: false,
    ownerOrgTeamId: '',
    sponsorOrgTeamId: '',
    tags: ['Documentation'],
    categoryNew: '',
    membersDevices: [casesInline],
    kbArticles: [casesInline0],
    metadataValues: casesMetadata,
};

export const updateWithInvalidIdPayload = {
    id: '02fcb243-166b-42464267-a10c-423546574',
    referenceNum: '13FA4A',
    remoteId: '',
    displayName: '',
    customerId: '46YSFE',
    customerName: 'Automation-3sbu266',
    customerEmail: 'bminchinton13@list-manage.com',
    customerLocationId: '46YSFE-7ME',
    customerLocationName: 'Automation-Szum269',
    customerContactId: '46YSFE-4FZ',
    customerContactName: 'Giuseppe',
    customerContactEmail: 'gkefford1k@stanford.edu',
    userId: '46YSFE-4FZ',
    externalId: '',
    type: 'Support',
    category: '',
    details: '',
    status: 'New',
    job: '',
    resolution: 'Not Set',
    created: Date.now().toString(),
    updated: Date.now().toString(),
    scheduledTime: '',
    enrouteTime: '',
    arrivalTime: '',
    departureTime: '',
    idrIsq: '',
    idrProcess: '',
    idrResolution: '',
    techSupportMinutes: 0,
    specialNotes: '',
    unmanaged: false,
    ownerOrgTeamId: '',
    sponsorOrgTeamId: '',
    tags: ['Documentation'],
    categoryNew: '',
    membersDevices: [casesInline],
    kbArticles: [casesInline0],
    metadataValues: casesMetadata,
};

export const casesCreatePayload = {
    cases: createPayload,
} as CasesCreateRequest;

export const casesUpdatePayload = {
    cases: updatePayload,
} as CasesCreateRequest;

export const casesCreateResponse = {
    success: true,
    totalCount: 1,
    returned: 1,
    pages: 3,
    results: {} as CasesModel,
    current_server_time: Date.now().toString(),
};

export const caseEscalateOptions = {
    orgTeamId: '341643652',
    userId: '54757478',
    notes: 'test notes',
    message: 'test message',
    alertCollaborators: true,
} as CaseEscalateOptions;

export const caseDeEscalateOptions = {
    orgTeamId: '341643652',
    userId: '54757478',
} as CaseDeEscalateOptions;

export const caseStatusHistoryModel = {
    created: Date.now().toString(),
    type: 'Support',
    status: 'New',
    resolution: 'Not Set',
    scheduled_time: '',
    ticketSummaryText: '',
    historySummaryText: '',
} as CaseStatusHistoryModel;

export const statusHistoryList = [
    {
        caseStatusHistoryModel,
    },
];

export const caseStatusHistoryResponse = {
    success: true,
    totalCount: 1,
    returned: statusHistoryList.length,
    pages: 0,
    results: JSON.parse(JSON.stringify(statusHistoryList)),
    current_server_time: Date.now().toString(),
} as CaseStatusHistoryResponseModel;

export const caseChatHistoryTranscriptModel = {
    chat_id: '02fcb243-166b-476b-a10c-44733013312a',
    participant: '',
    participant_id: '',
    timestamp: '',
    hadPayload: true,
    text: 'Test',
    user: 'Test',
    chat: '',
} as CaseChatHistoryTranscriptModel;

export const caseChatHistoryModel = {
    id: '02fcb243-166b-476b-1133s-44733013312a',
    object_id: '',
    object_scope: '',
    chat_type: 0,
    chat_status: 0,
    billing_status: 0,
    title: '',
    subtitle: '',
    duration_plus: 0,
    duration: 0,
    transcript: caseChatHistoryTranscriptModel,
    external_rpid: '',
    external_lpid: '',
    external_id: '',
    created: Date.now().toString(),
    updated: Date.now().toString(),
} as CaseChatHistoryModel;

export const chatHistoryList = [caseChatHistoryModel];

export const caseChatHistoryResponse = {
    success: true,
    totalCount: 1,
    returned: chatHistoryList.length,
    pages: 0,
    results: JSON.parse(JSON.stringify(chatHistoryList)),
    current_server_time: Date.now().toString(),
} as CaseChatHistoryResponseModel;

export const successResponse = {
    success: true,
    current_server_time: Date.now().toString(),
};

export const errorResponse = {
    success: false,
    errorType: 'FileNotFoundException',
    message: 'Unexpected error',
    current_server_time: Date.now().toString(),
};

export const accessDeniedResponse = {
    success: false,
    errorType: 'AccessDeniedException',
    message: 'Unable to schedule',
    current_server_time: Date.now().toString(),
};

export const caseIdErrorResponse = {
    success: false,
    errorType: 'FileNotFoundException',
    message: 'That Issue does not exist',
    current_server_time: Date.now().toString(),
};

export const scheduleTimeErrorResponse = {
    success: false,
    errorType: 'UserInputException',
    message: 'Invalid scheduledTime',
    current_server_time: Date.now().toString(),
};

export const cancelScheduleErrorResponse = {
    success: false,
    errorType: 'AccessDeniedException',
    message: 'Access Denied for new issues',
    current_server_time: Date.now().toString(),
};

export const statusErrorResponse = {
    success: false,
    errorType: 'Error',
    message: 'A Error has occurred',
    current_server_time: Date.now().toString(),
};

export const chatErrorResponse = {
    success: false,
    errorType: 'AccessDeniedException',
    message: 'Comm history for issue not available yet',
    current_server_time: Date.now().toString(),
};
