import {
    CustomerContact,
    CustomerLocation,
    Customer,
    UploadFile,
    CustomerProductSummary,
    CustomFormDataList,
} from '../../src/core/entity';
import { BaseResponseModel, CustomerTupleModel } from '../../src/core/models';

export const customerList = [
    {
        id: '27B79X',
        name: 'New_Customer_Created_1643738124596',
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-02-01 09:57:46',
        email: null,
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '2S6SZX',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2021-10-04 11:05:55',
        email: 'graffhyrum@gmail.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: '339WGC',
        name: 'Automation-3sbu266',
        name_legal: null,
        street_1: '0 Weeping Birch Crossing',
        street_2: 'Mayer',
        city: 'New York City',
        state: null,
        zipcode: '10280',
        latitude: 0,
        longitude: 0,
        industry: 'Retail',
        created: '2021-07-13 10:27:11',
        email: 'bminchinton13@list-manage.com',
        phone: '+1 (646) 319-8087',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '3NTPD6',
        name: 'Automation-Ehix967',
        name_legal: null,
        street_1: '00116 Buell Circle',
        street_2: 'Park Meadow',
        city: 'Portland',
        state: null,
        zipcode: '97271',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        created: '2021-07-13 10:18:05',
        email: 'pmilmoe4@g.co',
        phone: '+1 (971) 236-1286',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '46YSFE',
        name: 'Automation-Szum269',
        name_legal: null,
        street_1: '6442 Ilene Alley',
        street_2: 'Anthes',
        city: 'Decatur',
        state: null,
        zipcode: '30033',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        created: '2021-07-13 10:28:22',
        email: 'gkefford1k@opera.com',
        phone: '+1 (404) 395-8807',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '4MXBQB',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-28 07:26:03',
        email: 'cypress_chat_test197@test.com',
        phone: '+1 (684) 361-5121',
        status: 'Active',
        external_id: null,
    },
    {
        id: '4PJHK6',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 11:48:08',
        email: 'cypress9818@test.com',
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '4SLS9D',
        name: 'Automation-qwmt071',
        name_legal: null,
        street_1: '5 Old Shore Avenue',
        street_2: 'Lakeland',
        city: 'Evanston',
        state: null,
        zipcode: '60208',
        latitude: 0,
        longitude: 0,
        industry: 'National Restaurant',
        created: '2021-07-13 10:28:31',
        email: 'jyanne1m@booking.com',
        phone: '+1 (847) 933-6939',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '56KBH8',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-26 15:56:44',
        email: 'cypress44990@test.com',
        phone: '+1 (661) 279-6237',
        status: 'Active',
        external_id: null,
    },
    {
        id: '57B7RT',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 11:48:31',
        email: 'cypress72690@test.com',
        phone: '+1 (215) 801-4341',
        status: 'Active',
        external_id: null,
    },
    {
        id: '58FSPL',
        name: 'Automation-eHmc495',
        name_legal: null,
        street_1: '705 Longview Place',
        street_2: 'Swallow',
        city: 'Alexandria',
        state: null,
        zipcode: '22309',
        latitude: 0,
        longitude: 0,
        industry: 'National Retail',
        created: '2021-07-13 10:18:59',
        email: 'bpetryg@engadget.com',
        phone: '+1 (703) 370-6333',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '5EGDQZ',
        name: 'Automation-Coti166',
        name_legal: null,
        street_1: '09 Burrows Crossing',
        street_2: 'Duke',
        city: 'Sacramento',
        state: null,
        zipcode: '95894',
        latitude: 0,
        longitude: 0,
        industry: 'Medical / Dental',
        created: '2021-07-13 10:26:48',
        email: 'lurquhartx@so-net.ne.jp',
        phone: '+1 (916) 669-3866',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '5PLK9U',
        name: 'Automation-LIkg628',
        name_legal: null,
        street_1: '2812 Moulton Park',
        street_2: 'Troy',
        city: 'Nashville',
        state: null,
        zipcode: '37210',
        latitude: 0,
        longitude: 0,
        industry: 'Medical / Dental',
        created: '2021-07-13 10:27:52',
        email: 'csaiger1d@ning.com',
        phone: '+1 (615) 946-3995',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '5Q4CKR',
        name: 'Automation-qtip534',
        name_legal: null,
        street_1: '42866 Westport Hill',
        street_2: 'Pearson',
        city: 'Daytona Beach',
        state: null,
        zipcode: '32123',
        latitude: 0,
        longitude: 0,
        industry: 'Restaurant',
        created: '2021-07-13 10:27:29',
        email: 'dech17@hao123.com',
        phone: '+1 (386) 613-2384',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '647DLX',
        name: 'Automation-hKca977',
        name_legal: null,
        street_1: '80 Crescent Oaks Way',
        street_2: 'Spohn',
        city: 'Englewood',
        state: null,
        zipcode: '80150',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        created: '2021-07-13 10:18:36',
        email: 'lroddiea@wufoo.com',
        phone: '+1 (303) 932-4924',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '6S9YBU',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 12:38:30',
        email: 'cypress_chat_test57322@test.com',
        phone: '+1 (581) 548-1285',
        status: 'Active',
        external_id: null,
    },
    {
        id: '7YM8CR',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-28 07:57:57',
        email: 'cypress_chat_test77800@test.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: '86CW23',
        name: 'Automation-yfvq058',
        name_legal: null,
        street_1: '3864 Spohn Avenue',
        street_2: 'Beilfuss',
        city: 'Everett',
        state: null,
        zipcode: '98206',
        latitude: 0,
        longitude: 0,
        industry: 'National Retail',
        created: '2021-07-13 10:28:15',
        email: 'wnicholl1i@goodreads.com',
        phone: '+1 (425) 945-5584',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: '92SBNE',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 12:31:54',
        email: 'cypress61425@test.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: '9WDFRN',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 09:55:19',
        email: 'cypress54258@test.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: '9ZQZLN',
        name: 'Automation-eGis643',
        name_legal: null,
        street_1: '308 Evergreen Court',
        street_2: 'Kim',
        city: 'New Orleans',
        state: null,
        zipcode: '70187',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Restaurant',
        created: '2021-07-13 10:27:32',
        email: 'gcron18@google.it',
        phone: '+1 (504) 455-9513',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'AMVGNZ',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 12:44:50',
        email: 'cypress_chat_test7151@test.com',
        phone: '+1 (276) 429-8705',
        status: 'Active',
        external_id: null,
    },
    {
        id: 'AR454K',
        name: 'Automation-Dqnk420',
        name_legal: null,
        street_1: '851 Fallview Lane',
        street_2: 'Old Gate',
        city: 'Gadsden',
        state: null,
        zipcode: '35905',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2021-07-13 10:27:21',
        email: 'sheatlie15@hud.gov',
        phone: '+1 (256) 310-4125',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'AS5BC9',
        name: 'Automation-79oc150',
        name_legal: null,
        street_1: '9 Kinsman Drive',
        street_2: 'Bayside',
        city: 'Waco',
        state: null,
        zipcode: '76711',
        latitude: 0,
        longitude: 0,
        industry: 'National Restaurant',
        created: '2021-07-13 10:18:48',
        email: 'dschimaschked@sbwire.com',
        phone: '+1 (254) 456-5206',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'AVZWWT',
        name: 'Automation-cVqf162',
        name_legal: null,
        street_1: '53784 Dexter Circle',
        street_2: 'Village Green',
        city: 'Anchorage',
        state: null,
        zipcode: '99522',
        latitude: 0,
        longitude: 0,
        industry: 'Retail',
        created: '2021-07-13 10:28:27',
        email: 'tmullins1l@cnn.com',
        phone: '+1 (907) 607-1497',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'BESDSS',
        name: 'Automation-ists466',
        name_legal: null,
        street_1: '40689 Emmet Street',
        street_2: 'Duke',
        city: 'Huntington Beach',
        state: null,
        zipcode: '92648',
        latitude: 0,
        longitude: 0,
        industry: 'National Retail',
        created: '2021-07-13 10:19:04',
        email: 'asinesh@ftc.gov',
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'BZAV6J',
        name: 'Automation-1fri069',
        name_legal: null,
        street_1: '4 Hanover Point',
        street_2: 'Sheridan',
        city: 'Melbourne',
        state: null,
        zipcode: '32941',
        latitude: 0,
        longitude: 0,
        industry: 'Restaurant',
        created: '2021-07-13 10:18:55',
        email: 'jminillof@mozilla.org',
        phone: '+1 (321) 363-6624',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'C8J8AE',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2021-10-11 15:05:37',
        email: '123abc@boop.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: 'CQJUSZ',
        name: 'New_Customer_Created_1643756636804',
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-02-01 15:06:32',
        email: null,
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'DBF49S',
        name: 'New_Customer_Created_1643650821412',
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-31 09:41:46',
        email: null,
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'DXZ2YS',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 12:40:59',
        email: 'cypress_chat_test57061@test.com',
        phone: '+1 (630) 452-7598',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'DZRSFM',
        name: 'Automation-BKjp980',
        name_legal: null,
        street_1: '63 Norway Maple Terrace',
        street_2: 'Garrison',
        city: 'Rockford',
        state: null,
        zipcode: '61105',
        latitude: 0,
        longitude: 0,
        industry: 'National Retail',
        created: '2021-07-13 10:27:08',
        email: 'rsummerson12@angelfire.com',
        phone: '+1 (815) 928-5792',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'EBW2RS',
        name: 'Automation-69oo357',
        name_legal: null,
        street_1: '06263 Main Junction',
        street_2: 'Ridgeway',
        city: 'Nashville',
        state: null,
        zipcode: '37245',
        latitude: 0,
        longitude: 0,
        industry: 'National Retail',
        created: '2021-07-13 10:18:29',
        email: 'fferroni9@cbsnews.com',
        phone: '+1 (615) 723-8714',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'EWCNCB',
        name: 'SMS Recipient +1 (869) 888-7545',
        name_legal: 'SMS Recipient +1 (869) 888-7545',
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-02-03 00:47:23',
        email: null,
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: 'EYY6C6',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 11:42:35',
        email: 'cypress4733@test.com',
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: 'G5ELD4',
        name: 'Webchat Testing Customer',
        name_legal: 'WTC LLC',
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2021-12-08 13:24:43',
        email: null,
        phone: null,
        status: 'Active',
        external_id: null,
    },
    {
        id: 'GFG3Q5',
        name: 'Multi Location Customer',
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2021-08-31 11:21:27',
        email: null,
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'GJKJYE',
        name: 'Automation-2ixb012',
        name_legal: null,
        street_1: '52938 Tennessee Terrace',
        street_2: 'Nelson',
        city: 'Boston',
        state: null,
        zipcode: '02208',
        latitude: 0,
        longitude: 0,
        industry: 'Medical / Dental',
        created: '2021-07-13 10:32:55',
        email: 'talecock1t@howstuffworks.com',
        phone: '+1 (617) 686-0101',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'GWY8E9',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 11:46:58',
        email: 'cypress92427@test.com',
        phone: '+1 (435) 667-1283',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'GZFJC5',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 07:15:50',
        email: 'cypress21635@test.com',
        phone: '+1 (456) 292-8162',
        status: 'Active',
        external_id: null,
    },
    {
        id: 'H5QDLH',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-28 08:31:07',
        email: 'cypress_chat_test63468@test.com',
        phone: '+1 (890) 853-9116',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'HX2SYK',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-28 08:10:26',
        email: 'cypress_chat_test32552@test.com',
        phone: '+1 (426) 866-6724',
        status: 'Active',
        external_id: null,
    },
    {
        id: 'J8CYYD',
        name: 'Automation-26ol990',
        name_legal: null,
        street_1: '7 Havey Point',
        street_2: 'Cambridge',
        city: 'Brooklyn',
        state: null,
        zipcode: '11247',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Restaurant',
        created: '2021-07-13 10:23:41',
        email: 'fmatzelq@wunderground.com',
        phone: '+1 (212) 561-0681',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'JCSQBT',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-28 08:31:43',
        email: 'cypress_chat_test19181@test.com',
        phone: '+1 (583) 889-8225',
        status: 'Active',
        external_id: null,
    },
    {
        id: 'JVYXKE',
        name: 'Automation-pdks505',
        name_legal: null,
        street_1: '33377 Hoepker Street',
        street_2: 'Londonderry',
        city: 'Lincoln',
        state: null,
        zipcode: '68517',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Restaurant',
        created: '2021-07-13 10:38:51',
        email: 'ahaet21@tumblr.com',
        phone: '+1 (402) 376-0556',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'JVZU2N',
        name: null,
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-01-27 11:43:54',
        email: 'cypress63665@test.com',
        phone: '+1 (233) 366-3420',
        status: 'Active',
        external_id: null,
    },
    {
        id: 'K2XD7R',
        name: 'Automation-Pfha575',
        name_legal: null,
        street_1: '9 Drewry Crossing',
        street_2: 'Canary',
        city: 'Los Angeles',
        state: null,
        zipcode: '90060',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Retail',
        created: '2021-07-13 10:44:33',
        email: 'anoot2d@issuu.com',
        phone: '+1 (323) 215-6784',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'KUQLEH',
        name: 'Automation-oxbj850',
        name_legal: null,
        street_1: '04 Corben Avenue',
        street_2: 'La Follette',
        city: 'Fort Lauderdale',
        state: null,
        zipcode: '33345',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Retail',
        created: '2021-07-13 10:28:40',
        email: 'cbennis1o@blinklist.com',
        phone: '+1 (754) 577-7148',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'KY4SU5',
        name: 'Automation-FEtc222',
        name_legal: null,
        street_1: '554 Northfield Center',
        street_2: 'Forest Run',
        city: 'San Antonio',
        state: null,
        zipcode: '78240',
        latitude: 0,
        longitude: 0,
        industry: 'Mid-Market Retail',
        created: '2021-07-13 10:26:59',
        email: 'blennon10@apple.com',
        phone: '+1 (210) 257-6596',
        status: 'Inactive',
        external_id: null,
    },
    {
        id: 'LHC3GC',
        name: 'New_Customer_Created_1643759197526',
        name_legal: null,
        street_1: '',
        street_2: '',
        city: '',
        state: null,
        zipcode: '',
        latitude: 0,
        longitude: 0,
        industry: 'Other',
        created: '2022-02-01 15:49:01',
        email: null,
        phone: null,
        status: 'Inactive',
        external_id: null,
    },
];

export const customerResponse = {
    success: true,
    totalCount: 108,
    returned: customerList.length,
    pages: 3,
    results: JSON.parse(JSON.stringify(customerList)),
    current_server_time: Date.now().toString(),
};

export const createPayload = {
    customer: {
        id: '',
        name: 'Automation-Szum269',
        nameLegal: 'pk',
        street1: '6442 Ilene Alley',
        street2: 'Anthes',
        city: 'Decatur',
        state: 'null',
        zipcode: '30033',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        email: 'gkefford1k@opera.com',
        phone: '+1 (404) 395-8807',
        status: 'Inactive',
        externalId: 'null',
        created: new Date(),
    } as Customer,
    customerContact: {} as CustomerContact,
    customerLocation: {} as CustomerLocation,
    matchExternalId: false,
};

export const updatePayload = {
    customer: {
        id: '46YSFE',
        name: 'Automation-Szum269',
        nameLegal: 'ix',
        street1: '6442 Ilene Alley',
        street2: 'Anthes',
        city: 'Decatur',
        state: 'null',
        zipcode: '30033',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        email: 'gkefford1k@opera.com',
        phone: '+1 (404) 395-8807',
        status: 'Inactive',
        externalId: 'null',
        created: new Date(),
    } as Customer,
    customerContact: {} as CustomerContact,
    customerLocation: {
        customForms: {} as CustomFormDataList,
        files: [] as UploadFile[],
        products: {} as CustomerProductSummary,
    } as CustomerLocation,
    matchExternalId: false,
};

export const updateWithInvalidIdPayload = {
    customer: {
        id: '',
        name: 'Automation-Szum269',
        nameLegal: 'pk',
        street1: '6442 Ilene Alley',
        street2: 'Anthes',
        city: 'Decatur',
        state: 'null',
        zipcode: '30033',
        latitude: 0,
        longitude: 0,
        industry: 'Health & Beauty',
        email: 'gkefford1k@opera.com',
        phone: '+1 (404) 395-8807',
        status: 'Inactive',
        externalId: 'null',
        created: new Date(),
    },
    customer_user: {
        id: '',
        customerId: '',
        customerLocationId: 'string',
        firstName: 'string',
        lastName: 'string',
        fullName: 'string',
        email: 'string',
        smsNumber: 'string',
        externalId: 'string',
        lang: 'string',
    },
    customerLocation: {
        id: '',
        customerId: '',
        street1: 'string',
        street2: 'string',
        city: 'string',
        state: 'string',
        zipcode: 'string',
        latitude: 0,
        longitude: 0,
        phone: 'string',
        siteName: 'string',
        orgTeamIds: ['string'],
        externalId: '',
        notes: 'string',
        status: 'string',
        customForms: {},
        files: [
            [
                {
                    id: '',
                    object: 'string',
                    objectId: '',
                    type: 'string',
                    file: 'string',
                    size: 0,
                    name: 'string',
                    tag: 'string',
                    notes: 'string',
                    thumbnail: 'string',
                    created: '2022-02-13T18:13:34.152Z',
                },
            ],
        ],
        merchantIds: '',
        metadataValues: {
            locationProductsNotes: 'string',
            uniqueAspectsThatAffectConnectivity: 'string',
            terminalIdentificationNumber: 'string',
        },
        products: {
            id: '',
            parentId: '',
            type: 'string',
            critical: true,
            active: true,
            make: 'string',
            model: 'string',
            lastChecked: '2022-02-13T18:13:34.152Z',
            lastSeen: '2022-02-13T18:13:34.152Z',
            lastChanged: '2022-02-13T18:13:34.152Z',
            pciCompliant: 'string',
            policy: 'string',
            status: 'string',
        },
    },
    matchExternalId: true,
};

export const customerCreateResponse = {
    success: true,
    totalCount: 1,
    returned: customerList.length,
    pages: 1,
    results: {} as CustomerTupleModel,
    current_server_time: Date.now().toString(),
};

export const customerDeleteResponse: BaseResponseModel = {
    success: true,
    totalCount: 1,
    returned: 0,
    pages: 3,
    current_server_time: Date.now().toString(),
};

export const customerErrorResponse = {
    success: false,
    errorType: 'FileNotFoundException',
    message: 'Object Not Found for members 2S6SZX1',
    current_server_time: '2022-02-10T05:03:27+0000'
};

export const createSmsInvitePayload = {
    smsNumber: '9654104462',
    orgTeamId: ''
};

export const createInvalidSmsInvitePayload = {
    smsNumber: 'testing',
    orgTeamId: ''
};

export const smsInviteResponse = {
    current_server_time: Date.now().toString(),
    customerId: 'TKKPSB',
    inviteId: '7PJK23',
    issueId: '1b0c7112-f11c-41f1-8f2b-56816c34755c',
    success: true
};

export const smsInviteErrorResponse = {
    success: false,
    errorType: 'UserInputException',
    message: 'Missing/invalid sms_number parameter (sms_number)',
    fields: [
        'sms_number'
    ],
    current_server_time: Date.now().toString()
};

export const createCustomerErrorResponse = {
    success: false,
    errorType: 'FileNotFoundException',
    message: 'No match found for customer id/external_id parameter',
    current_server_time: '2022-02-10T05:03:27+0000',
};
