import { BoomtownConfig } from './boomtown-config';

export const apiPaths = {
    getCustomerApi: generatePath(`customers/get`),
    getCustomerByIdApi: (id: string) => generatePath(`customers/get/${id}`),
    createUpdateCustomerApi: generatePath(`customers/put`),
    deleteCustomerApi: (id: string) => generatePath(`customers/delete/${id}`),
    customerMetaStatus: generatePath(`customers/meta/statuses`),
    customerMetaIndustries: generatePath(`customers/meta/industries`),
    getCustomerLocationByIdApi: (id: string) => generatePath(`customers/location/get/${id}`),
    createUpdateCustomerLocationApi: generatePath(`customers/location/put`),
    deleteCustomerLocationApi: (id: string) => generatePath(`/customers/location/delete/${id}`),
    getCustomerLocationByExternalIdApi: generatePath(`customers/location/lookupByExternalId`),
    getCustomerLocationMetaStatus: generatePath(`customers/location/meta_statuses`),
    customerContactCheck: (email: string) => generatePath(`customers/user_check/${email}`),
    customerContactByCustomerId: (customerId: string) => generatePath(`customers/user/get/${customerId}`),
    customerContactByExternalId: generatePath(`customers/user/lookupByExternalId`),
    createUpdateCustomerContact: generatePath(`customers/user/put`),
    customerContactSSO: (contactId: string) => generatePath(`customers/user/sso/${contactId}`),
    deleteCustomerContact: (customerId: string) => generatePath(`customers/user/delete/${customerId}`),
    getCaseMetaStatusApi: generatePath('issues/meta/statuses'),
    getCaseMetaJobsApi: generatePath('issues/meta/jobs'),
    getCaseMetaCategoriesApi: generatePath('issues/meta/categories'),
    getCaseMetaCategoriesNewApi: generatePath('issues/meta/categories_new'),
    getCaseMetaTagsApi: generatePath('issues/meta/tags'),
    getCaseMetaTypesApi: generatePath('issues/meta/types'),
    getCaseMetaFileTagsApi: generatePath('issues/meta/file_tags'),
    getCaseMetaResolutionsApi: generatePath('issues/meta/resolutions'),
    getCasesApi: generatePath('issues/get'),
    getCasesByIdApi: (id: string) => generatePath(`issues/get/${id}`),
    createUpdateCasesApi: generatePath(`issues/put`),
    getCaseFileByIdApi: (issueId: string) => generatePath(`/issues/files/${issueId}`),
    caseFileUploadApi: (issueId: string) => generatePath(`/issues/file/upload/${issueId}`),
    deleteCaseFileByIdApi: (issueId: string) => generatePath(`/issues/file/delete/${issueId}`),
    createUpdateCaseLogApi:(issueId: string) => generatePath(`/issues/log/put/${issueId}`),
    customerLookup: generatePath('customers/lookup'),
    getLookupByIssueId: generatePath('customers/lookupByIssueId'),
    getLookupById: generatePath('customers/lookupById'),
    getLookupByEmail: generatePath('customers/lookupByEmail'),
    getLookupByExternalId: generatePath('customers/lookupByExternalId'),
    customerMetaCustomForms: generatePath('customers/meta/customForms'),
    customerSmsInviteApi: generatePath('customers/sms_invite'),
    customerPasswordResetApi: generatePath('customers/password_reset'),
    getCaseLogByIdApi: (issueId: string) => generatePath(`/issues/log/history/${issueId}`),
    deleteCaseLogApi: (issueId: string) => generatePath(`/issues/log/delete/${issueId}`),
    caseScheduleByIdApi: (issueId: string) => generatePath(`/issues/schedule/${issueId}`),
    caseCancelScheduleByIdApi: (issueId: string) => generatePath(`/issues/cancel_schedule/${issueId}`),
    caseResolveByIdApi: (issueId: string) => generatePath(`/issues/resolve/${issueId}`),
    caseEscalateByIdApi: (issueId: string) => generatePath(`/issues/escalate/${issueId}`),
    caseDeEscalateByIdApi: (issueId: string) => generatePath(`/issues/deescalate/${issueId}`),
    caseCancelByIdApi: (issueId: string) => generatePath(`/issues/cancel/${issueId}`),
    caseStatusByIdApi: (issueId: string) => generatePath(`/issues/status/history/${issueId}`),
    caseChatHistoryByIdApi: (issueId: string) => generatePath(`/issues/chat/history/${issueId}`),
};

function generatePath(path: string): string {
    return BoomtownConfig.baseApiUrl + path;
}
