"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiPaths = void 0;
var boomtown_config_1 = require("./boomtown-config");
exports.apiPaths = {
    getCustomerApi: generatePath("customers/get"),
    getCustomerByIdApi: function (id) { return generatePath("customers/get/".concat(id)); },
    createUpdateCustomerApi: generatePath("customers/put"),
    deleteCustomerApi: function (id) { return generatePath("customers/delete/".concat(id)); },
    customerMetaStatus: generatePath("customers/meta/statuses"),
    customerMetaIndustries: generatePath("customers/meta/industries"),
    getCustomerLocationByIdApi: function (id) { return generatePath("customers/location/get/".concat(id)); },
    createUpdateCustomerLocationApi: generatePath("customers/location/put"),
    deleteCustomerLocationApi: function (id) { return generatePath("/customers/location/delete/".concat(id)); },
    getCustomerLocationByExternalIdApi: generatePath("customers/location/lookupByExternalId"),
    getLocationContactByCustomerId: function (customerId) { return generatePath("/customers/location/users/".concat(customerId)); },
    getCustomerLocationMetaStatus: generatePath("customers/location/meta_statuses"),
    customerContactCheck: function (email) { return generatePath("customers/user_check/".concat(email)); },
    customerContactByCustomerId: function (customerId) { return generatePath("customers/user/get/".concat(customerId)); },
    customerContactByExternalId: generatePath("customers/user/lookupByExternalId"),
    createUpdateCustomerContact: generatePath("customers/user/put"),
    customerContactSSO: function (contactId) { return generatePath("customers/user/sso/".concat(contactId)); },
    deleteCustomerContact: function (customerId) { return generatePath("customers/user/delete/".concat(customerId)); },
    getCaseMetaStatusApi: generatePath('issues/meta/statuses'),
    getCaseMetaJobsApi: generatePath('issues/meta/jobs'),
    getCaseMetaCategoriesApi: generatePath('issues/meta/categories'),
    getCaseMetaCategoriesNewApi: generatePath('issues/meta/categories_new'),
    getCaseMetaTagsApi: generatePath('issues/meta/tags'),
    getCaseMetaTypesApi: generatePath('issues/meta/types'),
    getCaseMetaFileTagsApi: generatePath('issues/meta/file_tags'),
    getCaseMetaResolutionsApi: generatePath('issues/meta/resolutions'),
    getCasesApi: generatePath('issues/get'),
    getCasesByIdApi: function (id) { return generatePath("issues/get/".concat(id)); },
    createUpdateCasesApi: generatePath("issues/put"),
    getCaseFileByIdApi: function (issueId) { return generatePath("/issues/files/".concat(issueId)); },
    caseFileUploadApi: function (issueId) { return generatePath("/issues/file/upload/".concat(issueId)); },
    deleteCaseFileByIdApi: function (issueId) { return generatePath("/issues/file/delete/".concat(issueId)); },
    createUpdateCaseLogApi: function (issueId) { return generatePath("/issues/log/put/".concat(issueId)); },
    customerLookup: generatePath('customers/lookup'),
    getLookupByIssueId: generatePath('customers/lookupByIssueId'),
    getLookupById: generatePath('customers/lookupById'),
    getLookupByEmail: generatePath('customers/lookupByEmail'),
    getLookupByExternalId: generatePath('customers/lookupByExternalId'),
    customerMetaCustomForms: generatePath('customers/meta/customForms'),
    customerSmsInviteApi: generatePath('customers/sms_invite'),
    customerPasswordResetApi: generatePath('customers/password_reset'),
    getCaseLogByIdApi: function (issueId) { return generatePath("/issues/log/history/".concat(issueId)); },
    deleteCaseLogApi: function (issueId) { return generatePath("/issues/log/delete/".concat(issueId)); },
    caseScheduleByIdApi: function (issueId) { return generatePath("/issues/schedule/".concat(issueId)); },
    caseCancelScheduleByIdApi: function (issueId) { return generatePath("/issues/cancel_schedule/".concat(issueId)); },
    caseResolveByIdApi: function (issueId) { return generatePath("/issues/resolve/".concat(issueId)); },
    caseEscalateByIdApi: function (issueId) { return generatePath("/issues/escalate/".concat(issueId)); },
    caseDeEscalateByIdApi: function (issueId) { return generatePath("/issues/deescalate/".concat(issueId)); },
    caseCancelByIdApi: function (issueId) { return generatePath("/issues/cancel/".concat(issueId)); },
    caseStatusByIdApi: function (issueId) { return generatePath("/issues/status/history/".concat(issueId)); },
    caseChatHistoryByIdApi: function (issueId) { return generatePath("/issues/chat/history/".concat(issueId)); },
};
function generatePath(path) {
    return boomtown_config_1.BoomtownConfig.baseApiUrl + path;
}
//# sourceMappingURL=api-paths.js.map