steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=sdk/npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=sdk-package-keyring
  - --key=sdk-publish-key
  volumes:
  - name: 'home'
    path: /root/

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd sdk
    node -v 
    npm -v
    npm audit
    npm audit fix
    npm version 4.9.12-beta
    npm install -g --save
    npm run-script build
    npm publish --access public --tag beta
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/
