# name: Version Increment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.base_ref }}   # checkout the current branch name
#           fetch-depth: 2                # fetch the whole repo history

#       - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
#         run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

#       - name: Add tags
#         run: |
#               git config --global --add user.name 'sumits096'
#               git config --global --add user.email 'sumits@incubxperts.com's
#               git tag v$(cat package.json | grep version | head -1 | awk -F= "{ print $1 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
#               git push --tags
              
