name: Version Increment

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.head_ref }}   # checkout the correct branch name
        #   fetch-depth: 0                # fetch the whole repo history
        #   token: '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'
      # - run: env GIT_TERMINAL_PROMPT=1 go get https://github.com/sumits096/ix-npm-versioning
      # - run: git config --global --add url."ssh://git@github.com:".insteadOf "https://github.com/"
      - run: echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
      - run: git config --global --add user.name 'sumits096'
      - run: git config --global --add user.email 'sumits@incubxperts.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
