name: Version Increment

on:
  push:
    branches:
      - version-changes

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     submodules: 'true'
      #     token: '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'
      # - run: env GIT_TERMINAL_PROMPT=1 go get https://github.com/sumits096/ix-npm-versioning
      # - run: git config --global --add url."ssh://git@github.com:".insteadOf "https://github.com/"
      - run: git config --global --add user.name 'sumits096'
      - run: git config --global --add user.email 'sumits@incubxperts.com'
      - run: npm version patch
      - run: git push
