name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: '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'
      - run: git config --global --add url 'git@github.com:'
      - run: git config --global --add user.name 'sumits096'
      - run: git config --global --add user.email 'sumits@incubxperts.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
