name: Version Increment

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.head_ref }}   # checkout the correct branch name
        #   fetch-depth: 0                # fetch the whole repo history
        #   token: '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'
      # - run: env GIT_TERMINAL_PROMPT=1 go get https://github.com/sumits096/ix-npm-versioning
      # - run: git config --global --add url."ssh://git@github.com:".insteadOf "https://github.com/"
      - run: echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
      - run: echo ${{ github.head_ref }}
      # - run: git config --global --add user.name 'sumits096'
      # - run: git config --global --add user.email 'sumits@incubxperts.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push ${{ github.head_ref }}
      # - run: |
      #         echo "Slug variables"
      #         echo " - ${{ env.GITHUB_REF_SLUG }}"    
      #         echo " - ${{ env.GITHUB_HEAD_REF_SLUG }}"
      #         echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
      #         echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
      #         # output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
      #         echo "Slug URL variables"
      #         echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
      #         echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
      #         echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
      #         echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
      #         # output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
      #         echo "Short SHA variables"
      #         echo " - ${{ env.GITHUB_SHA_SHORT }}"
      #         # output e.g. : ffac537e
