name: Version Increment

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.head_ref }}   # checkout the correct branch name
        #   fetch-depth: 0                # fetch the whole repo history
        #   token: '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'
      # - run: echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
      # - run: echo ${{ github.head_ref }}
      # - run: git config --global --add user.name 'sumits096'
      # - run: git config --global --add user.email 'sumits@incubxperts.com'
      # - run: echo 'true condition'
      # - run: npm version patch -m "[RELEASE] %s"
      # - run: git merge FETCH_HEAD
      # - run: git push origin HEAD:refs/heads/${{ github.head_ref }} --force

      - name: Major version
        if: "'true' == 'true'"
        run: |
              echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
              echo ${{ github.head_ref }}
              git config --global --add user.name 'sumits096'
              git config --global --add user.email 'sumits@incubxperts.com'
              echo 'Add Major version'
              npm version major -m "[RELEASE] %s"
              git merge FETCH_HEAD
              git push origin HEAD:refs/heads/${{ github.head_ref }} --force
      
      - name: Minor version
        if: "'true' == 'true'"
        run: |
              echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
              echo ${{ github.head_ref }}
              git config --global --add user.name 'sumits096'
              git config --global --add user.email 'sumits@incubxperts.com'
              echo 'Add Minor version'
              npm version minor -m "[RELEASE] %s"
              git merge FETCH_HEAD
              git push origin HEAD:refs/heads/${{ github.head_ref }} --force

      - name: Patch version
        if: "'true' == 'true'"
        run: |
              echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
              echo ${{ github.head_ref }}
              git config --global --add user.name 'sumits096'
              git config --global --add user.email 'sumits@incubxperts.com'
              echo 'Add Patch version'
              npm version patch -m "[RELEASE] %s"
              git merge FETCH_HEAD
              git push origin HEAD:refs/heads/${{ github.head_ref }} --force
